import type { DecisionItem, LaneItem } from "./types.js";

export function seedLaneItems(): LaneItem[] {
  return [
    {
      ref: "ENQ-CONSOLE-001",
      lane: "leads",
      state: "social_enquiry_received",
      owner: "Taylor",
      outcome: "progressed",
      reason: "Taylor can classify this non-PII enquiry in TEST.",
    },
    {
      ref: "ENQ-CONSOLE-002",
      lane: "nurture",
      state: "nurture",
      owner: "Taylor",
      outcome: "progressed",
      reason: "Nurture sequence pointer already recorded.",
    },
    {
      ref: "ENQ-CONSOLE-003",
      lane: "sales",
      state: "qualification",
      owner: "Sam",
      outcome: "progressed",
      reason: "Sam can continue qualification with fixture evidence.",
    },
    {
      ref: "OFF-CONSOLE-001",
      lane: "offers",
      state: "offer_presented",
      owner: "Sam",
      outcome: "awaiting_external",
      reason: "Offer presented; waiting for client response (no PII stored).",
    },
    {
      ref: "pi_test_console_not_live",
      lane: "payments",
      state: "payment_pending",
      owner: "Sam",
      outcome: "awaiting_external",
      reason: "Stripe test-mode intent; Sam owns payment_clear.",
    },
    {
      ref: "CW-CONSOLE-001",
      lane: "closed_won",
      state: "payment_verified",
      owner: "Sam",
      outcome: "blocked",
      reason: "TEST blocks live Closed Won even with spoofed operating_mode or unlock evidence.",
    },
    {
      ref: "ONB-CONSOLE-001",
      lane: "onboarding",
      state: "onboarding_started",
      owner: "Jordan",
      outcome: "blocked",
      reason: "Explicit health consent missing; screening/Ready stay closed.",
    },
    {
      ref: "RDY-CONSOLE-001",
      lane: "screening_ready",
      state: "health_consent_recorded",
      owner: "Jordan",
      outcome: "blocked",
      reason: "Ready cannot bypass human evidence.",
    },
    {
      ref: "PROG-CONSOLE-001",
      lane: "screening_ready",
      state: "programme_draft",
      owner: "Founder",
      outcome: "founder_required",
      reason: "First-client programme assignment needs founder go-live approval.",
    },
    {
      ref: "COACH-CONSOLE-001",
      lane: "coaching",
      state: "active_coaching",
      owner: "Jordan",
      outcome: "progressed",
      reason: "Delivery codes only; no Zone C on the bus.",
    },
    {
      ref: "CHK-CONSOLE-001",
      lane: "checkins",
      state: "weekly_checkin_open",
      owner: "Jordan",
      outcome: "progressed",
      reason: "Open/close check-in codes can be planned as dry-run records.",
    },
    {
      ref: "ADH-CONSOLE-001",
      lane: "adherence",
      state: "adherence_escalation",
      owner: "Alex",
      outcome: "blocked",
      reason: "Adherence escalation routed to Alex; no health judgement.",
    },
    {
      ref: "CAN-CONSOLE-001",
      lane: "renewal_cancellation",
      state: "cancellation_requested",
      owner: "Founder",
      outcome: "founder_required",
      reason: "Refund/credit is a per-case founder decision; never automatic.",
    },
    {
      ref: "ASSET-CONSOLE-001",
      lane: "content",
      state: "social_qa_recorded",
      owner: "Taylor",
      outcome: "blocked",
      reason: "Exact-final TAYLOR PASS and CHATGPT PASS are missing.",
    },
    {
      ref: "PUBERR-CONSOLE-001",
      lane: "publication_errors",
      state: "social_qa_recorded",
      owner: "ChatGPT",
      outcome: "blocked",
      reason: "pass_checksum does not match asset_checksum; publication stays ineligible.",
    },
    {
      ref: "STRIPE-TEST",
      lane: "stripe",
      state: "payment_verified",
      owner: "Sam",
      outcome: "blocked",
      reason: "Trusted mode is TEST; live Stripe money movement is a hard stop.",
    },
    {
      ref: "BLK-CONSOLE-001",
      lane: "blockers",
      state: "blocked",
      owner: "Alex",
      outcome: "blocked",
      reason: "Grok_Alex: route this blocker; founder only if a founder gate applies.",
    },
    {
      ref: "JOB-CONSOLE-001",
      lane: "jobs",
      state: "queued",
      owner: "Cursor",
      outcome: "awaiting_external",
      reason: "Bounded dry-run job is queued, not completed.",
    },
    {
      ref: "DEC-CONSOLE-001",
      lane: "decisions",
      state: "pending",
      owner: "Founder",
      outcome: "founder_required",
      reason: "Founder Decision Inbox item is pending. Never approve-all.",
    },
  ];
}

export function seedDecisions(now: string): DecisionItem[] {
  const kinds: Array<Omit<DecisionItem, "createdAt">> = [
    {
      id: "dec_stripe_unlock",
      kind: "stripe_unlock",
      title: "Named founder Stripe-live/payment unlock",
      subjectRef: "FD-STRIPE-LIVE-CONTROLLED-BETA",
      status: "pending",
      founderGate: true,
      evidence: { founder_payment_unlock_ref: "FD-STRIPE-LIVE-CONTROLLED-BETA" },
      notes: "Separate from whole-business LIVE. Does not execute Stripe.",
    },
    {
      id: "dec_golive",
      kind: "first_client_programme_golive",
      title: "First-client programme go-live",
      subjectRef: "PROG-CONSOLE-001",
      status: "pending",
      founderGate: true,
      evidence: { programme_draft_ref: "PROG-DRAFT-CONSOLE", founder_golive_approval: false },
      notes: "Human Ready and founder approval remain required.",
    },
    {
      id: "dec_health_safety",
      kind: "health_safety",
      title: "Health/safety judgement request",
      subjectRef: "HS-CONSOLE-001",
      status: "pending",
      founderGate: true,
      evidence: { health_judgement: false },
      notes: "Hard stop. Console never issues a clinical judgement.",
    },
    {
      id: "dec_privacy_legal",
      kind: "privacy_legal",
      title: "Material privacy/legal exception",
      subjectRef: "PRIV-CONSOLE-001",
      status: "pending",
      founderGate: true,
      evidence: { privacy_legal_exception: false },
      notes: "Never automated. Drive remains policy SoT.",
    },
    {
      id: "dec_paid_spend",
      kind: "paid_spend",
      title: "Paid spend request",
      subjectRef: "SPEND-CONSOLE-001",
      status: "pending",
      founderGate: true,
      evidence: { paid_spend: false },
      notes: "Hard stop. No paid spend from this console.",
    },
    {
      id: "dec_security",
      kind: "irreversible_security",
      title: "Irreversible account/security change",
      subjectRef: "SEC-CONSOLE-001",
      status: "pending",
      founderGate: true,
      evidence: { irreversible_security: false },
      notes: "Founder only, outside this engine. TEST records the packet only.",
    },
  ];
  return kinds.map((item) => ({ ...item, createdAt: now }));
}
